"""fase 1-3: inventario, contabilidad, recurrencias, einvoice, outbox, webhooks, pasarelas

Revision ID: a59bfe4b97cf
Revises: e2f5f18d9f49
Create Date: 2026-09-17 17:50:52.325760
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a59bfe4b97cf'
down_revision: Union[str, None] = 'e2f5f18d9f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('signature_ok', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_webhook_provider_event')
    )
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_event_provider'), ['provider'], unique=False)

    op.create_table('einvoice_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=4), nullable=False),
    sa.Column('consecutive', sa.String(length=20), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=True),
    sa.Column('reference_clave', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hacienda_message', sa.Text(), nullable=True),
    sa.Column('xml_document', sa.Text(), nullable=True),
    sa.Column('xml_response', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('einvoice_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_einvoice_document_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_einvoice_document_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_einvoice_document_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to', sa.String(length=300), nullable=False),
    sa.Column('bcc', sa.String(length=600), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_outbox_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_category_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payment_gateway_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_gateway_tenant_provider')
    )
    with op.batch_alter_table('payment_gateway_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_gateway_config_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('iva_credit', sa.String(length=12), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_clave', sa.String(length=50), nullable=True),
    sa.Column('attachment_url', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(length=12), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_send', sa.Boolean(), nullable=False),
    sa.Column('auto_charge', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_invoice_id', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['last_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurrence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurrence_next_date'), ['next_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movement_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_warehouse_id'), ['warehouse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movement_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_product_id'))

    op.drop_table('stock_movement')
    with op.batch_alter_table('recurrence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrence_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_recurrence_next_date'))

    op.drop_table('recurrence')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_expense_date'))

    op.drop_table('expense')
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_tenant_id'))

    op.drop_table('warehouse')
    with op.batch_alter_table('payment_gateway_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_gateway_config_tenant_id'))

    op.drop_table('payment_gateway_config')
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_category_tenant_id'))

    op.drop_table('expense_category')
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_outbox_tenant_id'))

    op.drop_table('email_outbox')
    with op.batch_alter_table('einvoice_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_einvoice_document_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_einvoice_document_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_einvoice_document_clave'))

    op.drop_table('einvoice_document')
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_event_provider'))

    op.drop_table('webhook_event')
    # ### end Alembic commands ###
