"""2fa: codigos de recuperacion

Revision ID: cccf260a87ac
Revises: 7e1c061cd2e2
Create Date: 2026-09-23 08:13:04.567282
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cccf260a87ac'
down_revision: Union[str, None] = '7e1c061cd2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # la tabla user ya tiene filas: sin server_default no se puede agregar una columna NOT NULL
        batch_op.add_column(sa.Column('totp_recovery', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_recovery')

    # ### end Alembic commands ###
