"""sesion 6: soporte, mantenimientos y comisiones

Revision ID: 7e1c061cd2e2
Revises: 4b003b1253bd
Create Date: 2026-09-22 23:32:19.485215
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e1c061cd2e2'
down_revision: Union[str, None] = '4b003b1253bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base', sa.String(length=10), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_rule_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_rule_user_id'), ['user_id'], unique=False)

    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('base', sa.String(length=10), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('earned_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['commission_rule.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_earned_on'), ['earned_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_user_id'), ['user_id'], unique=False)

    op.create_table('maintenance_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('every_months', sa.Integer(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('last_done', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_contract_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_next_date'), ['next_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('opened_by', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['customer_asset.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['maintenance_contract.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_ticket_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('support_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_note_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_note_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_reason', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('approval_reason')

    with op.batch_alter_table('support_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_note_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_note_tenant_id'))

    op.drop_table('support_note')
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_ticket_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_priority'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_kind'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_customer_id'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_assigned_to'))

    op.drop_table('support_ticket')
    with op.batch_alter_table('maintenance_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_number'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_next_date'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_customer_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_active'))

    op.drop_table('maintenance_contract')
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_user_id'))
        batch_op.drop_index(batch_op.f('ix_commission_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_commission_status'))
        batch_op.drop_index(batch_op.f('ix_commission_payment_id'))
        batch_op.drop_index(batch_op.f('ix_commission_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_commission_earned_on'))

    op.drop_table('commission')
    with op.batch_alter_table('commission_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_rule_user_id'))
        batch_op.drop_index(batch_op.f('ix_commission_rule_tenant_id'))

    op.drop_table('commission_rule')
    # ### end Alembic commands ###
