"""fase 4-5: tienda, ordenes, cupones, recepcion, credenciales api

Revision ID: 2dfd279e2968
Revises: a59bfe4b97cf
Create Date: 2026-09-17 18:09:01.933766
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2dfd279e2968'
down_revision: Union[str, None] = 'a59bfe4b97cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_url', sa.String(length=400), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_credential_kid'), ['kid'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_credential_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('min_total', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_coupon_code')
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('store_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('in_nav', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_store_page_slug')
    )
    with op.batch_alter_table('store_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_page_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('shipping', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('coupon_code', sa.String(length=40), nullable=True),
    sa.Column('shipping_method', sa.String(length=80), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_line_order_id'), ['order_id'], unique=False)

    op.create_table('received_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('consecutive', sa.String(length=20), nullable=True),
    sa.Column('issuer_name', sa.String(length=200), nullable=True),
    sa.Column('issuer_id', sa.String(length=30), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('iva_condition', sa.String(length=12), nullable=False),
    sa.Column('activity_code', sa.String(length=10), nullable=True),
    sa.Column('action', sa.String(length=12), nullable=True),
    sa.Column('hacienda_status', sa.String(length=20), nullable=False),
    sa.Column('xml_document', sa.Text(), nullable=True),
    sa.Column('xml_response', sa.Text(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('received_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_received_document_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_document_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_received_document_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_received_document_clave'))

    op.drop_table('received_document')
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_line_order_id'))

    op.drop_table('order_line')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_number'))

    op.drop_table('order')
    with op.batch_alter_table('store_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_page_tenant_id'))

    op.drop_table('store_page')
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_tenant_id'))

    op.drop_table('coupon')
    with op.batch_alter_table('api_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_credential_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_credential_kid'))

    op.drop_table('api_credential')
    # ### end Alembic commands ###
