"""esquema inicial fase 0

Revision ID: e2f5f18d9f49
Revises: 
Create Date: 2026-09-17 10:56:31.446921
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2f5f18d9f49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sell', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('buy', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'currency', name='uq_fx_date_currency')
    )
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rate_date'), ['date'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('logo_url', sa.String(length=400), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bank', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('billing_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=4), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=3), nullable=False),
    sa.Column('terminal', sa.String(length=5), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('ecommerce', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'doc_type', 'prefix', name='uq_billing_group')
    )
    with op.batch_alter_table('billing_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_group_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('show_on_web', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_currency_tenant')
    )
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.String(length=12), nullable=False),
    sa.Column('id_number', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('whatsapp', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('exemption', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_id_number'), ['id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invoice',
    sa.Column('doc_type', sa.String(length=4), nullable=False),
    sa.Column('consecutive', sa.String(length=20), nullable=True),
    sa.Column('clave', sa.String(length=50), nullable=True),
    sa.Column('sale_condition', sa.String(length=4), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=4), nullable=False),
    sa.Column('balance', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('einvoice_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_sell', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('fx_buy', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('external_notes', sa.Text(), nullable=True),
    sa.Column('external_order', sa.String(length=60), nullable=True),
    sa.Column('activity_code', sa.String(length=10), nullable=True),
    sa.Column('medical_exemption_card', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quote',
    sa.Column('converted_invoice_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_sell', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('fx_buy', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('external_notes', sa.Text(), nullable=True),
    sa.Column('external_order', sa.String(length=60), nullable=True),
    sa.Column('activity_code', sa.String(length=10), nullable=True),
    sa.Column('medical_exemption_card', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['converted_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_tenant_id'), ['tenant_id'], unique=False)

    # Ciclo invoice.quote_id <-> quote.converted_invoice_id: la FK de invoice se agrega al final (Postgres valida el orden)
    op.create_foreign_key('fk_invoice_quote_id', 'invoice', 'quote', ['quote_id'], ['id'])

    op.create_table('payment_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=600), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_link_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_link_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('rate_code', sa.String(length=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['role.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_user')
    )
    with op.batch_alter_table('tenant_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_user_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_user_user_id'), ['user_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tip', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_event', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notify_customer', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('show_on_web', sa.Boolean(), nullable=False),
    sa.Column('description_invoice', sa.Text(), nullable=True),
    sa.Column('description_store', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=80), nullable=True),
    sa.Column('cabys_code', sa.String(length=13), nullable=True),
    sa.Column('cabys_description', sa.String(length=300), nullable=True),
    sa.Column('tariff_code', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_product_code')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invoice_line',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cabys_code', sa.String(length=13), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tax_code', sa.String(length=4), nullable=False),
    sa.Column('tax_rate_code', sa.String(length=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('product_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'tax_id', name='uq_product_tax')
    )
    op.create_table('quote_line',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cabys_code', sa.String(length=13), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tax_code', sa.String(length=4), nullable=False),
    sa.Column('tax_rate_code', sa.String(length=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_line_quote_id'), ['quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoice_quote_id', 'invoice', type_='foreignkey')
    with op.batch_alter_table('quote_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_line_quote_id'))

    op.drop_table('quote_line')
    op.drop_table('product_tax')
    with op.batch_alter_table('invoice_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_invoice_id'))

    op.drop_table('invoice_line')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_invoice_id'))

    op.drop_table('payment')
    with op.batch_alter_table('tenant_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_user_tenant_id'))

    op.drop_table('tenant_user')
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_tenant_id'))

    op.drop_table('tax')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_tenant_id'))

    op.drop_table('supplier')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_link_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_link_invoice_id'))

    op.drop_table('payment_link')
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quote_status'))
        batch_op.drop_index(batch_op.f('ix_quote_number'))

    op.drop_table('quote')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_number'))

    op.drop_table('invoice')
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_email'))

    op.drop_table('invitation')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_id_number'))

    op.drop_table('customer')
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_tenant_id'))

    op.drop_table('currency')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_tenant_id'))

    op.drop_table('category')
    with op.batch_alter_table('billing_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_group_tenant_id'))

    op.drop_table('billing_group')
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_tenant_id'))

    op.drop_table('bank_account')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_slug'))

    op.drop_table('tenant')
    op.drop_table('role')
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rate_date'))

    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
