"""sesion 5: oportunidades, levantamientos, proyectos, ordenes de trabajo, activos, compras y costo en catalogo

Revision ID: 4b003b1253bd
Revises: 76b0d5ff4a9a
Create Date: 2026-09-22 21:30:35.539862
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b003b1253bd'
down_revision: Union[str, None] = '76b0d5ff4a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('solution', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('next_action', sa.String(length=200), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('lost_reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_next_action_date'), ['next_action_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('techs', sa.Integer(), nullable=False),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_technician_id'), ['technician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_planned', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_labor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_travel', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_extra', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('survey_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_item_survey_id'), ['survey_id'], unique=False)

    op.create_table('survey_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_point_survey_id'), ['survey_id'], unique=False)

    op.create_table('purchase_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_request_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_request_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('helpers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_signature', sa.String(length=160), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('stock_applied', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_technician_id'), ['technician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('serial', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('mac', sa.String(length=32), nullable=True),
    sa.Column('firmware', sa.String(length=40), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_asset_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_asset_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_asset_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_asset_warranty_until'), ['warranty_until'], unique=False)

    op.create_table('purchase_request_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_request_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_request_line_request_id'), ['request_id'], unique=False)

    op.create_table('work_order_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('planned', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_material_work_order_id'), ['work_order_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=14, scale=4), nullable=True))
        batch_op.add_column(sa.Column('cost_currency', sa.String(length=3), nullable=False, server_default='USD'))
        batch_op.add_column(sa.Column('margin_pct', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('supplier_sku', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('supplier_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supplier_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_brand'), ['brand'], unique=False)

    # Ciclo opportunity.project_id <-> project.opportunity_id: la FK se agrega al final (Postgres valida el orden)
    op.create_foreign_key('fk_opportunity_project', 'opportunity', 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_opportunity_project', 'opportunity', type_='foreignkey')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_brand'))
        batch_op.drop_column('supplier_updated_at')
        batch_op.drop_column('supplier_stock')
        batch_op.drop_column('supplier_sku')
        batch_op.drop_column('model')
        batch_op.drop_column('brand')
        batch_op.drop_column('margin_pct')
        batch_op.drop_column('cost_currency')
        batch_op.drop_column('cost')

    with op.batch_alter_table('work_order_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_material_work_order_id'))

    op.drop_table('work_order_material')
    with op.batch_alter_table('purchase_request_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_request_line_request_id'))

    op.drop_table('purchase_request_line')
    with op.batch_alter_table('customer_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_asset_warranty_until'))
        batch_op.drop_index(batch_op.f('ix_customer_asset_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_asset_serial'))
        batch_op.drop_index(batch_op.f('ix_customer_asset_customer_id'))

    op.drop_table('customer_asset')
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_technician_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_status'))
        batch_op.drop_index(batch_op.f('ix_work_order_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_work_order_project_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_number'))
        batch_op.drop_index(batch_op.f('ix_work_order_customer_id'))

    op.drop_table('work_order')
    with op.batch_alter_table('purchase_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_request_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_request_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_request_number'))

    op.drop_table('purchase_request')
    with op.batch_alter_table('survey_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_point_survey_id'))

    op.drop_table('survey_point')
    with op.batch_alter_table('survey_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_item_survey_id'))

    op.drop_table('survey_item')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_number'))
        batch_op.drop_index(batch_op.f('ix_project_customer_id'))

    op.drop_table('project')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_survey_technician_id'))
        batch_op.drop_index(batch_op.f('ix_survey_status'))
        batch_op.drop_index(batch_op.f('ix_survey_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_survey_number'))
        batch_op.drop_index(batch_op.f('ix_survey_customer_id'))

    op.drop_table('survey')
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_status'))
        batch_op.drop_index(batch_op.f('ix_opportunity_owner_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_number'))
        batch_op.drop_index(batch_op.f('ix_opportunity_next_action_date'))

    op.drop_table('opportunity')
    # ### end Alembic commands ###
