"""orden: descuento por linea

Revision ID: 87ebc3b2b114
Revises: 2dfd279e2968
Create Date: 2026-09-17 18:13:19.798947
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87ebc3b2b114'
down_revision: Union[str, None] = '2dfd279e2968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_type', sa.String(length=8), nullable=False, server_default='percent'))
        batch_op.add_column(sa.Column('discount_value', sa.Numeric(precision=14, scale=5), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_type')

    # ### end Alembic commands ###
