"""sesion 4: multimedia, crm, variantes, planillas, conciliacion, eventos, soporte

Revision ID: 76b0d5ff4a9a
Revises: 87ebc3b2b114
Create Date: 2026-09-17 19:07:05.114615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76b0d5ff4a9a'
down_revision: Union[str, None] = '87ebc3b2b114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('iban', sa.String(length=40), nullable=True),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('spouse_credit', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_event_slug')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_media_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('support_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_grant_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bank_statement_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('batch', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('matched_type', sa.String(length=10), nullable=True),
    sa.Column('matched_id', sa.Integer(), nullable=True),
    sa.Column('matched_by', sa.String(length=10), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_line_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_line_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_line_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_line_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_line_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('receives_invoices', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contact_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contact_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_note_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_note_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ticket_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('max_per_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_type_event_id'), ['event_id'], unique=False)

    op.create_table('payroll_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('gross', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('ccss_worker', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('ccss_employer', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('provisions', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('rates', sa.JSON(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_run_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_variant_code')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payroll_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=160), nullable=False),
    sa.Column('base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overtime', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ccss_worker', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ccss_employer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('provisions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_line_run_id'), ['run_id'], unique=False)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('holder_name', sa.String(length=160), nullable=False),
    sa.Column('holder_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ticket_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('recurrence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=10), server_default='factura', nullable=False))
        batch_op.add_column(sa.Column('last_expense_id', sa.Integer(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_recurrence_last_expense_id', 'expense', ['last_expense_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurrence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recurrence_last_expense_id', type_='foreignkey')
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('last_expense_id')
        batch_op.drop_column('kind')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_order_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_event_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_code'))

    op.drop_table('ticket')
    with op.batch_alter_table('payroll_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_line_run_id'))

    op.drop_table('payroll_line')
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_product_variant_product_id'))

    op.drop_table('product_variant')
    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_run_tenant_id'))

    op.drop_table('payroll_run')
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_type_event_id'))

    op.drop_table('ticket_type')
    with op.batch_alter_table('customer_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_note_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_note_customer_id'))

    op.drop_table('customer_note')
    with op.batch_alter_table('customer_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contact_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_contact_customer_id'))

    op.drop_table('customer_contact')
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_date'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_batch'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_bank_account_id'))

    op.drop_table('bank_statement_line')
    with op.batch_alter_table('support_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_grant_tenant_id'))

    op.drop_table('support_grant')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_media_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_key'))

    op.drop_table('media')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_tenant_id'))

    op.drop_table('event')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_tenant_id'))

    op.drop_table('employee')
    # ### end Alembic commands ###
