"""Importa todos los modelos para que Alembic y Base.metadata los vean."""

from .base import TenantMixin, TimestampMixin
from .catalog import Category, Product, ProductTax, Supplier, Tax
from .core import (
    AccessRequest,
    AuditLog,
    Currency,
    ExchangeRate,
    Invitation,
    RefreshToken,
    Role,
    Tenant,
    TenantUser,
    User,
)
from .crm import Customer
from .extra import (
    BankStatementLine,
    CustomerContact,
    CustomerNote,
    Employee,
    Event,
    Media,
    PayrollLine,
    PayrollRun,
    ProductVariant,
    SupportGrant,
    Ticket,
    TicketType,
)
from .field import (
    CustomerAsset,
    Opportunity,
    Project,
    PurchaseRequest,
    PurchaseRequestLine,
    Survey,
    SurveyItem,
    SurveyObservation,
    SurveyPoint,
    WorkOrder,
    WorkOrderMaterial,
)
from .ops import (
    EInvoiceDocument,
    EmailOutbox,
    Expense,
    ExpenseCategory,
    PaymentGatewayConfig,
    Recurrence,
    StockMovement,
    Warehouse,
    WebhookEvent,
)
from .payments import BankAccount, Payment, PaymentLink
from .sales import BillingGroup, Invoice, InvoiceLine, Quote, QuoteAcceptance, QuoteLine, QuoteVersion
from .store import ApiCredential, Coupon, Order, OrderLine, ReceivedDocument, StorePage
from .support import (
    Commission,
    CommissionRule,
    MaintenanceContract,
    SupportNote,
    SupportTicket,
)

__all__ = [
    "TenantMixin",
    "TimestampMixin",
    "Tenant",
    "User",
    "TenantUser",
    "Role",
    "Invitation",
    "AccessRequest",
    "RefreshToken",
    "AuditLog",
    "Currency",
    "ExchangeRate",
    "Customer",
    "Product",
    "Category",
    "Tax",
    "ProductTax",
    "Supplier",
    "BillingGroup",
    "Quote",
    "QuoteLine",
    "QuoteVersion",
    "QuoteAcceptance",
    "Invoice",
    "InvoiceLine",
    "BankAccount",
    "Payment",
    "PaymentLink",
    "Warehouse",
    "StockMovement",
    "ExpenseCategory",
    "Expense",
    "Recurrence",
    "EInvoiceDocument",
    "EmailOutbox",
    "WebhookEvent",
    "PaymentGatewayConfig",
    "StorePage",
    "Coupon",
    "Order",
    "OrderLine",
    "ReceivedDocument",
    "ApiCredential",
    "Media",
    "CustomerContact",
    "CustomerNote",
    "ProductVariant",
    "Employee",
    "PayrollRun",
    "PayrollLine",
    "BankStatementLine",
    "Event",
    "TicketType",
    "Ticket",
    "SupportGrant",
    "Opportunity",
    "Survey",
    "SurveyPoint",
    "SurveyItem",
    "SurveyObservation",
    "Project",
    "WorkOrder",
    "WorkOrderMaterial",
    "CustomerAsset",
    "PurchaseRequest",
    "PurchaseRequestLine",
    "SupportTicket",
    "SupportNote",
    "MaintenanceContract",
    "CommissionRule",
    "Commission",
]
