"""Importa todos los modelos para que Alembic y Base.metadata los vean."""

from .base import TenantMixin, TimestampMixin
from .catalog import Category, Product, ProductTax, Supplier, Tax
from .core import (
    AuditLog,
    Currency,
    ExchangeRate,
    Invitation,
    RefreshToken,
    Role,
    Tenant,
    TenantUser,
    User,
)
from .crm import Customer
from .extra import (
    BankStatementLine,
    CustomerContact,
    CustomerNote,
    Employee,
    Event,
    Media,
    PayrollLine,
    PayrollRun,
    ProductVariant,
    SupportGrant,
    Ticket,
    TicketType,
)
from .ops import (
    EInvoiceDocument,
    EmailOutbox,
    Expense,
    ExpenseCategory,
    PaymentGatewayConfig,
    Recurrence,
    StockMovement,
    Warehouse,
    WebhookEvent,
)
from .payments import BankAccount, Payment, PaymentLink
from .sales import BillingGroup, Invoice, InvoiceLine, Quote, QuoteLine
from .store import ApiCredential, Coupon, Order, OrderLine, ReceivedDocument, StorePage

__all__ = [
    "TenantMixin",
    "TimestampMixin",
    "Tenant",
    "User",
    "TenantUser",
    "Role",
    "Invitation",
    "RefreshToken",
    "AuditLog",
    "Currency",
    "ExchangeRate",
    "Customer",
    "Product",
    "Category",
    "Tax",
    "ProductTax",
    "Supplier",
    "BillingGroup",
    "Quote",
    "QuoteLine",
    "Invoice",
    "InvoiceLine",
    "BankAccount",
    "Payment",
    "PaymentLink",
    "Warehouse",
    "StockMovement",
    "ExpenseCategory",
    "Expense",
    "Recurrence",
    "EInvoiceDocument",
    "EmailOutbox",
    "WebhookEvent",
    "PaymentGatewayConfig",
    "StorePage",
    "Coupon",
    "Order",
    "OrderLine",
    "ReceivedDocument",
    "ApiCredential",
    "Media",
    "CustomerContact",
    "CustomerNote",
    "ProductVariant",
    "Employee",
    "PayrollRun",
    "PayrollLine",
    "BankStatementLine",
    "Event",
    "TicketType",
    "Ticket",
    "SupportGrant",
]
